version: "3.9"
services:
  mysql:
    image: mariadb:10.8.3
    # Uncomment below when on Mac M1
    platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - museekapp_default
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - museekapp_default
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - MH_OUTGOING_HTTP_URL=http://host.docker.internal:8000/laravel-mailbox/hash/from/subject

networks:
  museekapp_default:
    external: true